language: go

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test ./beacons/ -v -covermode=count -coverprofile=coverage.out
  - if [ -a coverage.out ]; then $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci; fi;